### ISSUE TITLE
can somebody help me

### ISSUE THREAD

**Issue by qslia** [daodaofr/AlignPS#27]
(open-mmlab) a@b:~/AlignPS$ sh run_test.sh 
Traceback (most recent call last):
  File "./tools/test.py", line 13, in <module>
    from mmdet.apis import multi_gpu_test, single_gpu_test
  File "/home/a/AlignPS/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/a/AlignPS/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIAlign, RoIPool
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .cc_attention import CrissCrossAttention
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/cc_attention.py", line 10, in <module>
    '_ext', ['ca_forward', 'ca_backward', 'ca_map_forward', 'ca_map_backward'])
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: ca_forward miss in module _ext
Traceback (most recent call last):
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/a/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/test.py', '--local_rank=0', './configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0.py', 'work_dirs/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0/cuhk_alignps.pth', '--launcher', 'pytorch', '--out', 'work_dirs/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0/results_1000.pkl']' returned non-zero exit status 1.
------------------------

**Comment by qslia** [comment]
I have already installed mmcv=1.1.5 pytorch=1.7

**Comment by ZhengPeng7** [comment]
I met the same problem before. As I refer to the [mmcv installation docs](https://github.com/open-mmlab/mmcv#installation), there is no compatible version with mmcv==1.1.x+torch==1.7. In my env, I chose mmcv==1.1.5+torch==1.6.0, and you can download the pre-built mmcv-full [here](https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html) and install again to have a try.
